spring:
  datasource:
    #url: "jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    url: "jdbc:h2:file:./app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "app"
    password: "password"

# https://www.baeldung.com/sql-logging-spring-boot
#logging:
#  level:
#    org.hibernate:
#      orm.jdbc.bind: TRACE
#      type.descriptor.sql.BasicBinder: TRACE
#      SQL: DEBUG

# https://stackoverflow.com/questions/74862254/how-to-log-sql-statements-with-query-param-values-in-spring-boot-3-hibernate-6
#logging:
#  level:
#    sql: debug
#    org.hibernate.orm.jdbc.bind: trace
