#!/bin/bash
set -eo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

verbose=0

while getopts ":v" opt; do
  case $opt in
    v) verbose=1 ;;
    \?) echo "Invalid option: -$OPTARG" >&2; usage ;;
    :) echo "Option -$OPTARG requires an argument." >&2; usage ;;
  esac
done
shift $((OPTIND - 1))

if [ "$verbose" -eq 1 ]; then
  export APP_LOGGING_CONSOLE_LEVEL=debug
  export APP_LOGGING_CONSOLE_ENABLED=true
fi

"${SCRIPT_DIR}/../build/native/nativeCompile/jvmcli" "$@"
